version: 2
jobs: 
  build:
    
    working_directory: ~/circleci-marvel-api 

    docker: 
      - image: circleci/openjdk:8-jdk-stretch 

    steps: 

      - checkout 

      - restore_cache:

          key: marvel-api-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache: 
          paths:
            - ~/.m2
          key: marvel-api-{{ checksum "pom.xml" }}
      
      - run: mvn package 
      
      - store_test_results:
      
          path: target/surefire-reports
      
      - store_artifacts: 
      
          path: target/marvel-api-0.0.1-SNAPSHOT.jar
      